# coding: utf-8

"""
    orchd

    orchd API docs

    The version of the OpenAPI document: 10.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.backups_api import BackupsApi


class TestBackupsApi(unittest.TestCase):
    """BackupsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BackupsApi()

    def tearDown(self) -> None:
        pass

    def test_backup_website(self) -> None:
        """Test case for backup_website

        Create a website backup
        """
        pass

    def test_delete_website_backup(self) -> None:
        """Test case for delete_website_backup

        Delete a backup
        """
        pass

    def test_get_website_backup(self) -> None:
        """Test case for get_website_backup

        Get detailed metadata of the website backup
        """
        pass

    def test_get_website_backups(self) -> None:
        """Test case for get_website_backups

        Get all website backups metadata
        """
        pass

    def test_get_website_restore_status(self) -> None:
        """Test case for get_website_restore_status

        Get the last detailed metadata of the restored website backup.
        """
        pass

    def test_restore_website(self) -> None:
        """Test case for restore_website

        Restore website from a backup
        """
        pass


if __name__ == '__main__':
    unittest.main()
