# coding: utf-8

"""
    orchd

    orchd API docs

    The version of the OpenAPI document: 10.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.migration_details import MigrationDetails

class TestMigrationDetails(unittest.TestCase):
    """MigrationDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MigrationDetails:
        """Test MigrationDetails
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MigrationDetails`
        """
        model = MigrationDetails()
        if include_optional:
            return MigrationDetails(
                id = '',
                website_id = '',
                source_server_id = '',
                dest_server_id = '',
                dest_server_name = '',
                server_role = 'email',
                migration_status = 'queued',
                created_at = '',
                last_updated = '',
                website_primary_domain = '',
                percentage_complete = 56,
                session_id = ''
            )
        else:
            return MigrationDetails(
                id = '',
                website_id = '',
                source_server_id = '',
                dest_server_id = '',
                dest_server_name = '',
                server_role = 'email',
                migration_status = 'queued',
                created_at = '',
                last_updated = '',
                website_primary_domain = '',
                percentage_complete = 56,
                session_id = '',
        )
        """

    def testMigrationDetails(self):
        """Test MigrationDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
