# coding: utf-8

"""
    orchd

    orchd API docs

    The version of the OpenAPI document: 10.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.update_plan_default_server_group_id import UpdatePlanDefaultServerGroupId

class TestUpdatePlanDefaultServerGroupId(unittest.TestCase):
    """UpdatePlanDefaultServerGroupId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdatePlanDefaultServerGroupId:
        """Test UpdatePlanDefaultServerGroupId
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdatePlanDefaultServerGroupId`
        """
        model = UpdatePlanDefaultServerGroupId()
        if include_optional:
            return UpdatePlanDefaultServerGroupId(
                unset = True
            )
        else:
            return UpdatePlanDefaultServerGroupId(
                unset = True,
        )
        """

    def testUpdatePlanDefaultServerGroupId(self):
        """Test UpdatePlanDefaultServerGroupId"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
