# coding: utf-8

"""
    orchd

    orchd API docs

    The version of the OpenAPI document: 10.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.wordpress_api import WordpressApi


class TestWordpressApi(unittest.TestCase):
    """WordpressApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WordpressApi()

    def tearDown(self) -> None:
        pass

    def test_activate_wordpress_theme(self) -> None:
        """Test case for activate_wordpress_theme

        Activate a WordPress theme
        """
        pass

    def test_create_wordpress_user(self) -> None:
        """Test case for create_wordpress_user

        Create website WordPress user
        """
        pass

    def test_delete_wordpress_plugin(self) -> None:
        """Test case for delete_wordpress_plugin

        Delete website WordPress plugin
        """
        pass

    def test_delete_wordpress_theme(self) -> None:
        """Test case for delete_wordpress_theme

        Delete a WordPress theme
        """
        pass

    def test_delete_wordpress_user(self) -> None:
        """Test case for delete_wordpress_user

        Delete WordPress user
        """
        pass

    def test_get_default_wp_sso_user(self) -> None:
        """Test case for get_default_wp_sso_user

        """
        pass

    def test_get_word_press_maintenance_mode(self) -> None:
        """Test case for get_word_press_maintenance_mode

        Gets the MaintenanceMode for a WordPress installation
        """
        pass

    def test_get_word_press_siteurl(self) -> None:
        """Test case for get_word_press_siteurl

        Fetches the site URL for a WordPress installation
        """
        pass

    def test_get_wordpress_app_version(self) -> None:
        """Test case for get_wordpress_app_version

        Get WordPress version
        """
        pass

    def test_get_wordpress_config(self) -> None:
        """Test case for get_wordpress_config

        Get the WP config value for a given option
        """
        pass

    def test_get_wordpress_installations(self) -> None:
        """Test case for get_wordpress_installations

        Trigger discovery of WP installations
        """
        pass

    def test_get_wordpress_latest_version(self) -> None:
        """Test case for get_wordpress_latest_version

        Get WordPress latest available version
        """
        pass

    def test_get_wordpress_plugins(self) -> None:
        """Test case for get_wordpress_plugins

        Get website WordPress plugins
        """
        pass

    def test_get_wordpress_settings(self) -> None:
        """Test case for get_wordpress_settings

        Get Wordpress application settings
        """
        pass

    def test_get_wordpress_themes(self) -> None:
        """Test case for get_wordpress_themes

        Get website WordPress themes
        """
        pass

    def test_get_wordpress_user_sso_url(self) -> None:
        """Test case for get_wordpress_user_sso_url

        Get SSO URL for a WP user
        """
        pass

    def test_get_wordpress_users(self) -> None:
        """Test case for get_wordpress_users

        """
        pass

    def test_install_wordpress_plugin(self) -> None:
        """Test case for install_wordpress_plugin

        Install a plugin
        """
        pass

    def test_install_wordpress_theme(self) -> None:
        """Test case for install_wordpress_theme

        Install a WordPress theme
        """
        pass

    def test_set_default_wp_sso_user(self) -> None:
        """Test case for set_default_wp_sso_user

        Set WP user as the default SSO user for that website.
        """
        pass

    def test_set_word_press_maintenance_mode(self) -> None:
        """Test case for set_word_press_maintenance_mode

        Sets the MaintenanceMode for a WordPress installation
        """
        pass

    def test_set_word_press_siteurl(self) -> None:
        """Test case for set_word_press_siteurl

        Sets the site URL for a WordPress installation
        """
        pass

    def test_set_wordpress_config(self) -> None:
        """Test case for set_wordpress_config

        Set a single value of a wp-config.php entry.
        """
        pass

    def test_set_wordpress_theme_auto_update_status(self) -> None:
        """Test case for set_wordpress_theme_auto_update_status

        Set WordPress theme auto-update status
        """
        pass

    def test_update_wordpress_app_version(self) -> None:
        """Test case for update_wordpress_app_version

        Update website WP app to specific version or latest
        """
        pass

    def test_update_wordpress_plugin_settings(self) -> None:
        """Test case for update_wordpress_plugin_settings

        Updates website WordPress plugin settings
        """
        pass

    def test_update_wordpress_plugin_to_latest(self) -> None:
        """Test case for update_wordpress_plugin_to_latest

        Updates website WordPress plugin to latest version
        """
        pass

    def test_update_wordpress_settings(self) -> None:
        """Test case for update_wordpress_settings

        Update Wordpress app settings
        """
        pass

    def test_update_wordpress_theme(self) -> None:
        """Test case for update_wordpress_theme

        Update a WordPress theme
        """
        pass

    def test_update_wordpress_user(self) -> None:
        """Test case for update_wordpress_user

        Update WordPress user
        """
        pass


if __name__ == '__main__':
    unittest.main()
