# coding: utf-8

"""
    orchd

    orchd API docs

    The version of the OpenAPI document: 10.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.branding import Branding

class TestBranding(unittest.TestCase):
    """Branding unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Branding:
        """Test Branding
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Branding`
        """
        model = Branding()
        if include_optional:
            return Branding(
                org_name = '',
                parent = '',
                control_panel_domain = '',
                php_my_admin_domain = '',
                roundcube_domain = '',
                logo_path = '',
                inverse_logo_path = '',
                inverse_icon_path = '',
                login_image_path = '',
                favicon_path = '',
                name_servers = [
                    ''
                    ],
                settings = [
                    openapi_client.models.setting.Setting(
                        name = '', 
                        value = null, )
                    ],
                staging_domain = '',
                locale = 'af'
            )
        else:
            return Branding(
                org_name = '',
                settings = [
                    openapi_client.models.setting.Setting(
                        name = '', 
                        value = null, )
                    ],
                locale = 'af',
        )
        """

    def testBranding(self):
        """Test Branding"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
