# coding: utf-8

"""
    orchd

    orchd API docs

    The version of the OpenAPI document: 10.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.update_wp_user import UpdateWpUser

class TestUpdateWpUser(unittest.TestCase):
    """UpdateWpUser unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateWpUser:
        """Test UpdateWpUser
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateWpUser`
        """
        model = UpdateWpUser()
        if include_optional:
            return UpdateWpUser(
                password = '',
                name = '',
                email = ''
            )
        else:
            return UpdateWpUser(
        )
        """

    def testUpdateWpUser(self):
        """Test UpdateWpUser"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
