# coding: utf-8

"""
    orchd

    orchd API docs

    The version of the OpenAPI document: 10.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.import_migration_log_entry import ImportMigrationLogEntry

class TestImportMigrationLogEntry(unittest.TestCase):
    """ImportMigrationLogEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ImportMigrationLogEntry:
        """Test ImportMigrationLogEntry
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ImportMigrationLogEntry`
        """
        model = ImportMigrationLogEntry()
        if include_optional:
            return ImportMigrationLogEntry(
                id = '',
                created_at = '',
                migration_id = '',
                log_data = '',
                percentage_complete = 56,
                level = 'info',
                action = 'create',
                kind = 'migration'
            )
        else:
            return ImportMigrationLogEntry(
                id = '',
                created_at = '',
                migration_id = '',
                log_data = '',
                percentage_complete = 56,
                level = 'info',
                action = 'create',
                kind = 'migration',
        )
        """

    def testImportMigrationLogEntry(self):
        """Test ImportMigrationLogEntry"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
