# coding: utf-8

"""
    orchd

    orchd API docs

    The version of the OpenAPI document: 10.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.new_resource_id import NewResourceId

class TestNewResourceId(unittest.TestCase):
    """NewResourceId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NewResourceId:
        """Test NewResourceId
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NewResourceId`
        """
        model = NewResourceId()
        if include_optional:
            return NewResourceId(
                id = 56
            )
        else:
            return NewResourceId(
                id = 56,
        )
        """

    def testNewResourceId(self):
        """Test NewResourceId"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
