# coding: utf-8

"""
    orchd

    orchd API docs

    The version of the OpenAPI document: 10.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.recursion import Recursion

class TestRecursion(unittest.TestCase):
    """Recursion unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRecursion(self):
        """Test Recursion"""
        # inst = Recursion()

if __name__ == '__main__':
    unittest.main()
