# coding: utf-8

"""
    orchd

    orchd API docs

    The version of the OpenAPI document: 10.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.uuid_listing import UuidListing

class TestUuidListing(unittest.TestCase):
    """UuidListing unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UuidListing:
        """Test UuidListing
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UuidListing`
        """
        model = UuidListing()
        if include_optional:
            return UuidListing(
                ids = [
                    ''
                    ]
            )
        else:
            return UuidListing(
                ids = [
                    ''
                    ],
        )
        """

    def testUuidListing(self):
        """Test UuidListing"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
