# coding: utf-8

"""
    orchd

    orchd API docs

    The version of the OpenAPI document: 10.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.network_status import NetworkStatus

class TestNetworkStatus(unittest.TestCase):
    """NetworkStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetworkStatus(self):
        """Test NetworkStatus"""
        # inst = NetworkStatus()

if __name__ == '__main__':
    unittest.main()
