# coding: utf-8

"""
    orchd

    orchd API docs

    The version of the OpenAPI document: 10.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.my_sql_users_full_listing import MySQLUsersFullListing

class TestMySQLUsersFullListing(unittest.TestCase):
    """MySQLUsersFullListing unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MySQLUsersFullListing:
        """Test MySQLUsersFullListing
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MySQLUsersFullListing`
        """
        model = MySQLUsersFullListing()
        if include_optional:
            return MySQLUsersFullListing(
                items = [
                    openapi_client.models.my_sql_user.MySQLUser(
                        id = '', 
                        db_id = '', 
                        username = '', 
                        access_hosts = [
                            ''
                            ], 
                        auth_plugin = 'caching_sha2_password', 
                        grants = openapi_client.models.grants.grants(), 
                        created_at = '', 
                        is_ephemeral = True, )
                    ]
            )
        else:
            return MySQLUsersFullListing(
                items = [
                    openapi_client.models.my_sql_user.MySQLUser(
                        id = '', 
                        db_id = '', 
                        username = '', 
                        access_hosts = [
                            ''
                            ], 
                        auth_plugin = 'caching_sha2_password', 
                        grants = openapi_client.models.grants.grants(), 
                        created_at = '', 
                        is_ephemeral = True, )
                    ],
        )
        """

    def testMySQLUsersFullListing(self):
        """Test MySQLUsersFullListing"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
