# coding: utf-8

"""
    orchd

    orchd API docs

    The version of the OpenAPI document: 10.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.update_website_subscription_id import UpdateWebsiteSubscriptionId

class TestUpdateWebsiteSubscriptionId(unittest.TestCase):
    """UpdateWebsiteSubscriptionId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateWebsiteSubscriptionId:
        """Test UpdateWebsiteSubscriptionId
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateWebsiteSubscriptionId`
        """
        model = UpdateWebsiteSubscriptionId()
        if include_optional:
            return UpdateWebsiteSubscriptionId(
                unset = True
            )
        else:
            return UpdateWebsiteSubscriptionId(
                unset = True,
        )
        """

    def testUpdateWebsiteSubscriptionId(self):
        """Test UpdateWebsiteSubscriptionId"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
