# coding: utf-8

"""
    orchd

    orchd API docs

    The version of the OpenAPI document: 10.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.owner_api import OwnerApi


class TestOwnerApi(unittest.TestCase):
    """OwnerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OwnerApi()

    def tearDown(self) -> None:
        pass

    def test_delete_owner(self) -> None:
        """Test case for delete_owner

        Delete organization owner
        """
        pass

    def test_update_owner(self) -> None:
        """Test case for update_owner

        Update organization owner
        """
        pass


if __name__ == '__main__':
    unittest.main()
