# coding: utf-8

"""
    orchd

    orchd API docs

    The version of the OpenAPI document: 10.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.tags_full_listing import TagsFullListing

class TestTagsFullListing(unittest.TestCase):
    """TagsFullListing unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TagsFullListing:
        """Test TagsFullListing
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TagsFullListing`
        """
        model = TagsFullListing()
        if include_optional:
            return TagsFullListing(
                items = [
                    openapi_client.models.tag.Tag(
                        id = 56, 
                        tag = '', 
                        color_code = '', )
                    ]
            )
        else:
            return TagsFullListing(
                items = [
                    openapi_client.models.tag.Tag(
                        id = 56, 
                        tag = '', 
                        color_code = '', )
                    ],
        )
        """

    def testTagsFullListing(self):
        """Test TagsFullListing"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
