# coding: utf-8

"""
    orchd

    orchd API docs

    The version of the OpenAPI document: 10.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.servers_listing import ServersListing

class TestServersListing(unittest.TestCase):
    """ServersListing unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServersListing:
        """Test ServersListing
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServersListing`
        """
        model = ServersListing()
        if include_optional:
            return ServersListing(
                items = [
                    openapi_client.models.server_info_brief.ServerInfoBrief(
                        id = '', 
                        group_id = '', 
                        is_control_panel = True, 
                        is_configured = True, 
                        friendly_name = '', 
                        hostname = '', 
                        ips = [
                            openapi_client.models.server_ip.ServerIp(
                                ip = '', 
                                is_primary = True, )
                            ], 
                        roles = openapi_client.models.role_installed_status_summary.RoleInstalledStatusSummary(
                            application = 'enabled', 
                            backup = 'enabled', 
                            database = 'enabled', 
                            dns = 'enabled', 
                            email = 'enabled', ), 
                        created_at = '', 
                        dedicated_subscription = 1.337, 
                        is_decommissioned = True, 
                        ipv6_addr = '', )
                    ],
                total = 56
            )
        else:
            return ServersListing(
                items = [
                    openapi_client.models.server_info_brief.ServerInfoBrief(
                        id = '', 
                        group_id = '', 
                        is_control_panel = True, 
                        is_configured = True, 
                        friendly_name = '', 
                        hostname = '', 
                        ips = [
                            openapi_client.models.server_ip.ServerIp(
                                ip = '', 
                                is_primary = True, )
                            ], 
                        roles = openapi_client.models.role_installed_status_summary.RoleInstalledStatusSummary(
                            application = 'enabled', 
                            backup = 'enabled', 
                            database = 'enabled', 
                            dns = 'enabled', 
                            email = 'enabled', ), 
                        created_at = '', 
                        dedicated_subscription = 1.337, 
                        is_decommissioned = True, 
                        ipv6_addr = '', )
                    ],
                total = 56,
        )
        """

    def testServersListing(self):
        """Test ServersListing"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
