# coding: utf-8

"""
    orchd

    orchd API docs

    The version of the OpenAPI document: 10.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.control_role_info import ControlRoleInfo

class TestControlRoleInfo(unittest.TestCase):
    """ControlRoleInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ControlRoleInfo:
        """Test ControlRoleInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ControlRoleInfo`
        """
        model = ControlRoleInfo()
        if include_optional:
            return ControlRoleInfo(
                usage = 56,
                authd = openapi_client.models.core_service_info.CoreServiceInfo(
                    id = '', 
                    version = '', 
                    status = 'unknown', 
                    port = 56, 
                    usage = 56, 
                    processes = [
                        openapi_client.models.process_info.ProcessInfo(
                            pid = 56, 
                            name = '', 
                            cpu_usage = 1.337, 
                            res_memory = 56, )
                        ], ),
                sged = openapi_client.models.core_service_info.CoreServiceInfo(
                    id = '', 
                    version = '', 
                    status = 'unknown', 
                    port = 56, 
                    usage = 56, 
                    processes = [
                        openapi_client.models.process_info.ProcessInfo(
                            pid = 56, 
                            name = '', 
                            cpu_usage = 1.337, 
                            res_memory = 56, )
                        ], ),
                logd = openapi_client.models.core_service_info.CoreServiceInfo(
                    id = '', 
                    version = '', 
                    status = 'unknown', 
                    port = 56, 
                    usage = 56, 
                    processes = [
                        openapi_client.models.process_info.ProcessInfo(
                            pid = 56, 
                            name = '', 
                            cpu_usage = 1.337, 
                            res_memory = 56, )
                        ], )
            )
        else:
            return ControlRoleInfo(
                usage = 56,
                authd = openapi_client.models.core_service_info.CoreServiceInfo(
                    id = '', 
                    version = '', 
                    status = 'unknown', 
                    port = 56, 
                    usage = 56, 
                    processes = [
                        openapi_client.models.process_info.ProcessInfo(
                            pid = 56, 
                            name = '', 
                            cpu_usage = 1.337, 
                            res_memory = 56, )
                        ], ),
                sged = openapi_client.models.core_service_info.CoreServiceInfo(
                    id = '', 
                    version = '', 
                    status = 'unknown', 
                    port = 56, 
                    usage = 56, 
                    processes = [
                        openapi_client.models.process_info.ProcessInfo(
                            pid = 56, 
                            name = '', 
                            cpu_usage = 1.337, 
                            res_memory = 56, )
                        ], ),
                logd = openapi_client.models.core_service_info.CoreServiceInfo(
                    id = '', 
                    version = '', 
                    status = 'unknown', 
                    port = 56, 
                    usage = 56, 
                    processes = [
                        openapi_client.models.process_info.ProcessInfo(
                            pid = 56, 
                            name = '', 
                            cpu_usage = 1.337, 
                            res_memory = 56, )
                        ], ),
        )
        """

    def testControlRoleInfo(self):
        """Test ControlRoleInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
