# coding: utf-8

"""
    orchd

    orchd API docs

    The version of the OpenAPI document: 10.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.smart_host_settings_host import SmartHostSettingsHost

class TestSmartHostSettingsHost(unittest.TestCase):
    """SmartHostSettingsHost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SmartHostSettingsHost:
        """Test SmartHostSettingsHost
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SmartHostSettingsHost`
        """
        model = SmartHostSettingsHost()
        if include_optional:
            return SmartHostSettingsHost(
                hostname = '',
                port = 56
            )
        else:
            return SmartHostSettingsHost(
                hostname = '',
        )
        """

    def testSmartHostSettingsHost(self):
        """Test SmartHostSettingsHost"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
