# coding: utf-8

"""
    orchd

    orchd API docs

    The version of the OpenAPI document: 10.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.migration_session_creation_ok import MigrationSessionCreationOk

class TestMigrationSessionCreationOk(unittest.TestCase):
    """MigrationSessionCreationOk unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MigrationSessionCreationOk:
        """Test MigrationSessionCreationOk
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MigrationSessionCreationOk`
        """
        model = MigrationSessionCreationOk()
        if include_optional:
            return MigrationSessionCreationOk(
                session_id = '',
                ok_count = 56,
                migrations = [
                    openapi_client.models.migration_creation_outcome.MigrationCreationOutcome(
                        error = openapi_client.models.http_error.HttpError(
                            code = '', 
                            detail = '', 
                            message = '', ), 
                        migration_id = '', )
                    ]
            )
        else:
            return MigrationSessionCreationOk(
                session_id = '',
                ok_count = 56,
                migrations = [
                    openapi_client.models.migration_creation_outcome.MigrationCreationOutcome(
                        error = openapi_client.models.http_error.HttpError(
                            code = '', 
                            detail = '', 
                            message = '', ), 
                        migration_id = '', )
                    ],
        )
        """

    def testMigrationSessionCreationOk(self):
        """Test MigrationSessionCreationOk"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
