# coding: utf-8

"""
    orchd

    orchd API docs

    The version of the OpenAPI document: 10.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.server_stat_entry import ServerStatEntry

class TestServerStatEntry(unittest.TestCase):
    """ServerStatEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServerStatEntry:
        """Test ServerStatEntry
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServerStatEntry`
        """
        model = ServerStatEntry()
        if include_optional:
            return ServerStatEntry(
                server_id = '',
                io_wait = 1.337,
                ram_usage = 1.337,
                swap_usage = 1.337,
                system_load = 1.337,
                uptime = 1.337,
                recorded_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return ServerStatEntry(
                server_id = '',
                io_wait = 1.337,
                ram_usage = 1.337,
                swap_usage = 1.337,
                system_load = 1.337,
                uptime = 1.337,
                recorded_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testServerStatEntry(self):
        """Test ServerStatEntry"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
