# coding: utf-8

"""
    orchd

    orchd API docs

    The version of the OpenAPI document: 10.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.my_sqldbs_full_listing import MySQLDBsFullListing

class TestMySQLDBsFullListing(unittest.TestCase):
    """MySQLDBsFullListing unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MySQLDBsFullListing:
        """Test MySQLDBsFullListing
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MySQLDBsFullListing`
        """
        model = MySQLDBsFullListing()
        if include_optional:
            return MySQLDBsFullListing(
                items = [
                    openapi_client.models.my_sqldb.MySQLDB(
                        id = '', 
                        name = '', 
                        server_id = '', 
                        website_id = '', 
                        size = 56, 
                        created_at = '', )
                    ]
            )
        else:
            return MySQLDBsFullListing(
                items = [
                    openapi_client.models.my_sqldb.MySQLDB(
                        id = '', 
                        name = '', 
                        server_id = '', 
                        website_id = '', 
                        size = 56, 
                        created_at = '', )
                    ],
        )
        """

    def testMySQLDBsFullListing(self):
        """Test MySQLDBsFullListing"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
