# coding: utf-8

"""
    orchd

    orchd API docs

    The version of the OpenAPI document: 10.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.website_clone_response import WebsiteCloneResponse

class TestWebsiteCloneResponse(unittest.TestCase):
    """WebsiteCloneResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WebsiteCloneResponse:
        """Test WebsiteCloneResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WebsiteCloneResponse`
        """
        model = WebsiteCloneResponse()
        if include_optional:
            return WebsiteCloneResponse(
                id = '',
                source_website_id = '',
                dest_website_id = '',
                exclude_paths = [
                    ''
                    ],
                include_databases = [
                    ''
                    ],
                include_database_users = [
                    ''
                    ],
                delete_files_from_destination = True,
                status = 'queued',
                sync_php_version = True
            )
        else:
            return WebsiteCloneResponse(
                id = '',
                source_website_id = '',
                exclude_paths = [
                    ''
                    ],
                include_databases = [
                    ''
                    ],
                include_database_users = [
                    ''
                    ],
                delete_files_from_destination = True,
                status = 'queued',
                sync_php_version = True,
        )
        """

    def testWebsiteCloneResponse(self):
        """Test WebsiteCloneResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
