# coding: utf-8

"""
    orchd

    orchd API docs

    The version of the OpenAPI document: 10.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.migration_sessions_listing import MigrationSessionsListing

class TestMigrationSessionsListing(unittest.TestCase):
    """MigrationSessionsListing unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MigrationSessionsListing:
        """Test MigrationSessionsListing
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MigrationSessionsListing`
        """
        model = MigrationSessionsListing()
        if include_optional:
            return MigrationSessionsListing(
                items = [
                    openapi_client.models.migration_session_details.MigrationSessionDetails(
                        id = '', 
                        created_by = '', 
                        created_at = '', 
                        updated_at = '', 
                        migrations_count = 56, 
                        percentage_complete = 1.337, 
                        not_ready_count = 56, )
                    ],
                total = 56
            )
        else:
            return MigrationSessionsListing(
                items = [
                    openapi_client.models.migration_session_details.MigrationSessionDetails(
                        id = '', 
                        created_by = '', 
                        created_at = '', 
                        updated_at = '', 
                        migrations_count = 56, 
                        percentage_complete = 1.337, 
                        not_ready_count = 56, )
                    ],
                total = 56,
        )
        """

    def testMigrationSessionsListing(self):
        """Test MigrationSessionsListing"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
