# coding: utf-8

"""
    orchd

    orchd API docs

    The version of the OpenAPI document: 10.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.emails_api import EmailsApi


class TestEmailsApi(unittest.TestCase):
    """EmailsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EmailsApi()

    def tearDown(self) -> None:
        pass

    def test_create_website_email(self) -> None:
        """Test case for create_website_email

        Create an email under website's domain
        """
        pass

    def test_create_website_email_autoresponder(self) -> None:
        """Test case for create_website_email_autoresponder

        Create new website email autoresponder
        """
        pass

    def test_delete_website_email(self) -> None:
        """Test case for delete_website_email

        Delete website email
        """
        pass

    def test_delete_website_email_autoresponder(self) -> None:
        """Test case for delete_website_email_autoresponder

        Delete website email autoresponder
        """
        pass

    def test_get_domain_email_auth(self) -> None:
        """Test case for get_domain_email_auth

        Get email authentication preferences
        """
        pass

    def test_get_domain_local_remote(self) -> None:
        """Test case for get_domain_local_remote

        Get the current local/remote status
        """
        pass

    def test_get_emails(self) -> None:
        """Test case for get_emails

        Get org emails
        """
        pass

    def test_get_website_email(self) -> None:
        """Test case for get_website_email

        Get website email
        """
        pass

    def test_get_website_email_autoresponders(self) -> None:
        """Test case for get_website_email_autoresponders

        Get website email autoresponders
        """
        pass

    def test_get_website_email_client_conf(self) -> None:
        """Test case for get_website_email_client_conf

        Get website email client configuration
        """
        pass

    def test_get_website_emails(self) -> None:
        """Test case for get_website_emails

        Get website emails
        """
        pass

    def test_set_domain_local_remote(self) -> None:
        """Test case for set_domain_local_remote

        Update email local/remote status
        """
        pass

    def test_update_domain_email_auth(self) -> None:
        """Test case for update_domain_email_auth

        Update email authentication preferences
        """
        pass

    def test_update_website_email(self) -> None:
        """Test case for update_website_email

        Update website email
        """
        pass

    def test_update_website_email_autoresponder(self) -> None:
        """Test case for update_website_email_autoresponder

        Update website email autoresponder
        """
        pass

    def test_validate_domain_email_auth(self) -> None:
        """Test case for validate_domain_email_auth

        Validate email authentication DNS records
        """
        pass


if __name__ == '__main__':
    unittest.main()
