# coding: utf-8

"""
    orchd

    orchd API docs

    The version of the OpenAPI document: 10.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.wp_plugin_status import WPPluginStatus

class TestWPPluginStatus(unittest.TestCase):
    """WPPluginStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWPPluginStatus(self):
        """Test WPPluginStatus"""
        # inst = WPPluginStatus()

if __name__ == '__main__':
    unittest.main()
