# coding: utf-8

"""
    orchd

    orchd API docs

    The version of the OpenAPI document: 10.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.website_status import WebsiteStatus

class TestWebsiteStatus(unittest.TestCase):
    """WebsiteStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWebsiteStatus(self):
        """Test WebsiteStatus"""
        # inst = WebsiteStatus()

if __name__ == '__main__':
    unittest.main()
