# coding: utf-8

"""
    orchd

    orchd API docs

    The version of the OpenAPI document: 10.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.service_log import ServiceLog

class TestServiceLog(unittest.TestCase):
    """ServiceLog unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServiceLog:
        """Test ServiceLog
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServiceLog`
        """
        model = ServiceLog()
        if include_optional:
            return ServiceLog(
                created_at = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                service_kind = 'mysqld',
                status = 'ok',
                metadata = None
            )
        else:
            return ServiceLog(
                created_at = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                service_kind = 'mysqld',
                status = 'ok',
        )
        """

    def testServiceLog(self):
        """Test ServiceLog"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
