# coding: utf-8

"""
    orchd

    orchd API docs

    The version of the OpenAPI document: 10.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.server_status_action import ServerStatusAction

class TestServerStatusAction(unittest.TestCase):
    """ServerStatusAction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testServerStatusAction(self):
        """Test ServerStatusAction"""
        # inst = ServerStatusAction()

if __name__ == '__main__':
    unittest.main()
