# coding: utf-8

"""
    orchd

    orchd API docs

    The version of the OpenAPI document: 10.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.server_memory_usage import ServerMemoryUsage

class TestServerMemoryUsage(unittest.TestCase):
    """ServerMemoryUsage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServerMemoryUsage:
        """Test ServerMemoryUsage
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServerMemoryUsage`
        """
        model = ServerMemoryUsage()
        if include_optional:
            return ServerMemoryUsage(
                ram = openapi_client.models.space_usage.SpaceUsage(
                    total = 56, 
                    used = 56, ),
                swap = openapi_client.models.space_usage.SpaceUsage(
                    total = 56, 
                    used = 56, )
            )
        else:
            return ServerMemoryUsage(
                ram = openapi_client.models.space_usage.SpaceUsage(
                    total = 56, 
                    used = 56, ),
                swap = openapi_client.models.space_usage.SpaceUsage(
                    total = 56, 
                    used = 56, ),
        )
        """

    def testServerMemoryUsage(self):
        """Test ServerMemoryUsage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
