# coding: utf-8

"""
    orchd

    orchd API docs

    The version of the OpenAPI document: 10.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.dns_role_info import DnsRoleInfo

class TestDnsRoleInfo(unittest.TestCase):
    """DnsRoleInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DnsRoleInfo:
        """Test DnsRoleInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DnsRoleInfo`
        """
        model = DnsRoleInfo()
        if include_optional:
            return DnsRoleInfo(
                state = 'enabled',
                usage = 56,
                zones_count = 56,
                dnscd = openapi_client.models.service_info.ServiceInfo(
                    id = '', 
                    version = '', 
                    status = 'unknown', 
                    port = 56, 
                    usage = 56, 
                    processes = [
                        openapi_client.models.process_info.ProcessInfo(
                            pid = 56, 
                            name = '', 
                            cpu_usage = 1.337, 
                            res_memory = 56, )
                        ], ),
                websites_count = 56
            )
        else:
            return DnsRoleInfo(
                state = 'enabled',
                usage = 56,
                zones_count = 56,
                dnscd = openapi_client.models.service_info.ServiceInfo(
                    id = '', 
                    version = '', 
                    status = 'unknown', 
                    port = 56, 
                    usage = 56, 
                    processes = [
                        openapi_client.models.process_info.ProcessInfo(
                            pid = 56, 
                            name = '', 
                            cpu_usage = 1.337, 
                            res_memory = 56, )
                        ], ),
                websites_count = 56,
        )
        """

    def testDnsRoleInfo(self):
        """Test DnsRoleInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
