# coding: utf-8

"""
    orchd

    orchd API docs

    The version of the OpenAPI document: 10.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.customers_listing import CustomersListing

class TestCustomersListing(unittest.TestCase):
    """CustomersListing unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CustomersListing:
        """Test CustomersListing
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CustomersListing`
        """
        model = CustomersListing()
        if include_optional:
            return CustomersListing(
                items = [
                    openapi_client.models.org.Org(
                        id = '', 
                        parent_id = '', 
                        name = '', 
                        status = 'active', 
                        suspended_by = '', 
                        owner = '', 
                        owner_email = '', 
                        owner_id = '', 
                        owner_login_id = '', 
                        subscriptions_count = 56, 
                        websites_count = 56, 
                        created_at = '', 
                        owner_avatar_path = '', 
                        locale = 'af', 
                        slack_notification_webhook_url = '', )
                    ],
                total = 56
            )
        else:
            return CustomersListing(
                items = [
                    openapi_client.models.org.Org(
                        id = '', 
                        parent_id = '', 
                        name = '', 
                        status = 'active', 
                        suspended_by = '', 
                        owner = '', 
                        owner_email = '', 
                        owner_id = '', 
                        owner_login_id = '', 
                        subscriptions_count = 56, 
                        websites_count = 56, 
                        created_at = '', 
                        owner_avatar_path = '', 
                        locale = 'af', 
                        slack_notification_webhook_url = '', )
                    ],
                total = 56,
        )
        """

    def testCustomersListing(self):
        """Test CustomersListing"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
