# coding: utf-8

"""
    orchd

    orchd API docs

    The version of the OpenAPI document: 10.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.backup_action import BackupAction
from openapi_client.models.operation_status import OperationStatus
from typing import Optional, Set
from typing_extensions import Self

class BackupStatus(BaseModel):
    """
    BackupStatus
    """ # noqa: E501
    id: StrictInt
    website_id: StrictStr = Field(alias="websiteId")
    started_at: StrictStr = Field(alias="startedAt")
    action: BackupAction
    home_dir_status: Optional[OperationStatus] = Field(default=None, alias="homeDirStatus")
    mysql_dbs_status: Optional[OperationStatus] = Field(default=None, alias="mysqlDbsStatus")
    emails_status: Optional[OperationStatus] = Field(default=None, alias="emailsStatus")
    __properties: ClassVar[List[str]] = ["id", "websiteId", "startedAt", "action", "homeDirStatus", "mysqlDbsStatus", "emailsStatus"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BackupStatus from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BackupStatus from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "websiteId": obj.get("websiteId"),
            "startedAt": obj.get("startedAt"),
            "action": obj.get("action"),
            "homeDirStatus": obj.get("homeDirStatus"),
            "mysqlDbsStatus": obj.get("mysqlDbsStatus"),
            "emailsStatus": obj.get("emailsStatus")
        })
        return _obj


