# coding: utf-8

"""
    orchd

    orchd API docs

    The version of the OpenAPI document: 10.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.mysql_kind import MysqlKind
from openapi_client.models.php_version import PhpVersion
from typing import Optional, Set
from typing_extensions import Self

class CanUse(BaseModel):
    """
    CanUse
    """ # noqa: E501
    ftp: StrictBool
    file_manager: StrictBool = Field(alias="fileManager")
    php_versions: List[PhpVersion] = Field(alias="phpVersions")
    redis: StrictBool
    mod_sec: StrictBool = Field(alias="modSec")
    backup: StrictBool
    mysql_kind: Optional[MysqlKind] = Field(default=None, alias="mysqlKind")
    __properties: ClassVar[List[str]] = ["ftp", "fileManager", "phpVersions", "redis", "modSec", "backup", "mysqlKind"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CanUse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CanUse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "ftp": obj.get("ftp"),
            "fileManager": obj.get("fileManager"),
            "phpVersions": obj.get("phpVersions"),
            "redis": obj.get("redis"),
            "modSec": obj.get("modSec"),
            "backup": obj.get("backup"),
            "mysqlKind": obj.get("mysqlKind")
        })
        return _obj


