# coding: utf-8

"""
    orchd

    orchd API docs

    The version of the OpenAPI document: 10.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class DnsStatus(str, Enum):
    """
    Resolved = domain resolves to our servers. ForeignServer = domain resolves but points to somewhere else. Failed = DNS query failed for the domain (potentially not configured). Unknown = Not queried. Error = There was an internal error. Mixed = Website's domains resolved with different statuses.
    """

    """
    allowed enum values
    """
    RESOLVED = 'Resolved'
    FOREIGNSERVER = 'ForeignServer'
    FAILED = 'Failed'
    MIXED = 'Mixed'
    UNKNOWN = 'Unknown'
    ERROR = 'Error'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DnsStatus from a JSON string"""
        return cls(json.loads(json_str))


