# coding: utf-8

"""
    orchd

    orchd API docs

    The version of the OpenAPI document: 10.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Union
from typing import Optional, Set
from typing_extensions import Self

class MetricsEntry(BaseModel):
    """
    Each Metrics entry represts an hourly window of banwidth usage Note: depending upon the polling time, most recent hour values might not       be complete yet and are subject to change if fetched at a later time.
    """ # noqa: E501
    datetime: datetime = Field(description="Time at the beginning of the unit for this bandwidth consumption entry")
    bytes_received: Union[StrictFloat, StrictInt] = Field(alias="bytesReceived")
    bytes_sent: Union[StrictFloat, StrictInt] = Field(alias="bytesSent")
    unique_hits: Union[StrictFloat, StrictInt] = Field(alias="uniqueHits")
    bot_hits: Union[StrictFloat, StrictInt] = Field(alias="botHits")
    total_hits: Union[StrictFloat, StrictInt] = Field(alias="totalHits")
    __properties: ClassVar[List[str]] = ["datetime", "bytesReceived", "bytesSent", "uniqueHits", "botHits", "totalHits"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MetricsEntry from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MetricsEntry from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "datetime": obj.get("datetime"),
            "bytesReceived": obj.get("bytesReceived"),
            "bytesSent": obj.get("bytesSent"),
            "uniqueHits": obj.get("uniqueHits"),
            "botHits": obj.get("botHits"),
            "totalHits": obj.get("totalHits")
        })
        return _obj


