# coding: utf-8

"""
    orchd

    orchd API docs

    The version of the OpenAPI document: 10.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.website_app_kind import WebsiteAppKind
from typing import Optional, Set
from typing_extensions import Self

class NewWebsiteApp(BaseModel):
    """
    NewWebsiteApp
    """ # noqa: E501
    app: WebsiteAppKind
    version: Optional[StrictStr] = None
    path: Optional[StrictStr] = None
    admin_username: StrictStr = Field(description="This username is going to be the username of the initial WP user with which the user can login to the WP admin. This is equivalent to going to `wp-admin/install.php` and performing the install from there.", alias="adminUsername")
    admin_password: StrictStr = Field(description="Complements the admin username. Provide unhashed password.", alias="adminPassword")
    admin_email: StrictStr = Field(description="Sets the admin email address, required by some applications.", alias="adminEmail")
    domain_id: Optional[StrictStr] = Field(default=None, description="Install on a specific domain within this website.  Will default to use the primary domain.", alias="domainId")
    __properties: ClassVar[List[str]] = ["app", "version", "path", "adminUsername", "adminPassword", "adminEmail", "domainId"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NewWebsiteApp from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NewWebsiteApp from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "app": obj.get("app"),
            "version": obj.get("version"),
            "path": obj.get("path"),
            "adminUsername": obj.get("adminUsername"),
            "adminPassword": obj.get("adminPassword"),
            "adminEmail": obj.get("adminEmail"),
            "domainId": obj.get("domainId")
        })
        return _obj


