# coding: utf-8

"""
    orchd

    orchd API docs

    The version of the OpenAPI document: 10.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ResourceName(str, Enum):
    """
    The name of the resource. Must be unique within a plan. Note: for arbitrary string casting please use `camelCase` format
    """

    """
    allowed enum values
    """
    CUSTOMERS = 'customers'
    DISKSPACE = 'diskspace'
    DOMAINALIASES = 'domainAliases'
    FORWARDERS = 'forwarders'
    FTPUSERS = 'ftpUsers'
    MAILBOXES = 'mailboxes'
    MYSQLDBS = 'mysqlDbs'
    PAGEVIEWS = 'pageViews'
    PROCESSES = 'processes'
    STAGINGWEBSITES = 'stagingWebsites'
    TRANSFER = 'transfer'
    WEBSITES = 'websites'
    ADDONDOMAINS = 'addonDomains'
    SUBDOMAINS = 'subdomains'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ResourceName from a JSON string"""
        return cls(json.loads(json_str))


