# coding: utf-8

"""
    orchd

    orchd API docs

    The version of the OpenAPI document: 10.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class WebserverKind(str, Enum):
    """
    WebserverKind
    """

    """
    allowed enum values
    """
    LITESPEED = 'liteSpeed'
    OPENLITESPEED = 'openLiteSpeed'
    DUMMYWEBSERVER = 'dummyWebServer'
    APACHE = 'apache'
    NGINX = 'nginx'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of WebserverKind from a JSON string"""
        return cls(json.loads(json_str))


